<?php

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct() ?>

<?php
$redHotCount = $block->getRedHotCount();
if ($redHotCount > 0): ?>
    <div class="red-hot-counter field">
        <?= __('%1 customers love this product!', /* @noEscape */ $redHotCount) ?>
    </div>
<?php endif; ?>
<?php if ($_product->isSaleable() && $block->hasOptions()): ?>
    <div class="bundle-actions">
        <button id="bundle-slide"
                class="action primary customize"
                type="button">
            <span><?= $escaper->escapeHtml(__('Customize and Add to Cart')) ?></span>
        </button>
    </div>
<?php endif;?>
